name: Homegate Android UI Test
on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: check java version
        run: java -version
      - name: check where java
        run: which java
      - name: where is JAVA_HOME
        run: echo $JAVA_HOME
      - name: check node version
        run: node -v
      


