name: Homegate Android UI Test
on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: check java version
        run: java -version
      - name: check where java
        run: which java
      - name: where is JAVA_HOME /usr/lib/jvm/temurin-11-jdk-amd64
        run: echo $JAVA_HOME
      - name: check node version
        run: node -v
      - name: check device list
        run: avdmanager list device
      - name: install and start appium
        run: |
              npm install -g appium@next
              appium -v
              which appium
              appium driver install uiautomator2
              appium driver list
              appium &>/dev/null &

#       - name: Run Automation Tests
#         uses: reactivecircus/android-emulator-runner@v2
#         with:
#           api-level: 30
#           target: default
#           arch: x86_64
#           profile: Pixel XL
#           script: ./gradlew :test

      


