name: Homegate Android macOS
on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: check java version
        run: java -version
      - name: check where java
        run: which java
      - name: where is JAVA_HOME /usr/lib/jvm/temurin-11-jdk-amd64
        run: echo $JAVA_HOME
      - name: check node version
        run: node -v
      - name: check the android home /usr/local/lib/android/sdk
        run: echo $ANDROID_HOME
      - name: install and start appium
        run: |
              npm install -g appium@next
              appium -v
              which appium
              appium driver install uiautomator2
              appium driver list
              appium &>/dev/null &

      - name: Run Automation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: arm64-v8a
          profile: Pixel XL
          script: ./gradlew :test

      


