name: Homegate iOS UI Test
on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-12
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: check java version
        run: java -version
      - name: check where java
        run: which java
      - name: where is JAVA_HOME /Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.345-1/x64/Contents/Home/
        run: echo $JAVA_HOME 
      - name: check node version
        run: node -v
      - name: specify Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_13.4.1.app/Contents/Developer
      


